[logger]
level = "debug"
output_paths = ["stdout","stderr"]
error_output_paths = ["stderr"]

[database]
driver = "postgres"
host = "pgs"
port = "5432"
storage = "sql"
user = ""
db_name = ""
password = ""
ssl_mode = "disable"

[http]
host = "0.0.0.0"
port = "8080"
read_timeout = "200ms"
write_timeout = "200ms"
read_header_timeout = "200ms"

[http_logger]
level = "debug"
output_paths = ["stdout"]
error_output_paths = ["stderr"]

[grpc_logger]
level = "debug"
output_paths = ["stdout"]
error_output_paths = ["stderr"]

[grpc]
host="0.0.0.0"
port="50052"
