[logger]
level = "debug"
output_paths = ["stdout","stderr"]
error_output_paths = ["stderr"]

[database]
driver = "postgres"
host = "localhost"
port = "5433"
storage = "sql"
user = "calendar"
db_name = "calendar"
password = "developer"
ssl_mode = "disable"

[http]
host = "localhost"
port = "8080"
read_timeout = "200ms"
write_timeout = "200ms"
read_header_timeout = "200ms"

[http_logger]
level = "debug"
output_paths = ["./logs/http_server.log", "stdout"]
error_output_paths = ["stderr"]

[grpc_logger]
level = "debug"
output_paths = ["./logs/grpc_server.log", "stdout"]
error_output_paths = ["stderr"]

[grpc]
host="0.0.0.0"
port="50052"
