[logger]
level = "debug"
output_paths = ["stdout"]
error_output_paths = ["stderr"]

[database]
driver = "postgres"
host = "localhost"
port = "5433"
storage = "sql"
user = "calendar"
db_name = "calendar"
password = "developer"
ssl_mode = "disable"

[scheduler]
duration="10s"

[producer]
user="guest"
password="guest"
host="0.0.0.0"
port="5672"
queue_name="test_consumer"
consumer_name="calendar-app"
max_retries=20
