[logger]
level = "debug"
output_paths = ["stdout"]
error_output_paths = ["stderr"]

[database]
driver = "postgres"
host = "pgs"
port = "5432"
storage = "sql"
user = ""
db_name = ""
password = ""
ssl_mode = "disable"

[scheduler]
duration="10s"

[producer]
user=""
password=""
host="rabbitmq"
port="5672"
queue_name=""
consumer_name=""
max_retries=20
