[logger]
level = "debug"
output_paths = ["stdout"]
error_output_paths = ["stderr"]

[consumer]
user="guest"
password="guest"
host="0.0.0.0"
port="5672"
queue_name="test_consumer"
consumer_name="calendar-app"
max_retries=20
