[logger]
level = "debug"
output_paths = ["stdout"]
error_output_paths = ["stderr"]

[consumer]
user="guest"
password=""
host="rabbitmq"
port="5672"
queue_name=""
consumer_name=""
max_retries=20

[database]
driver = "postgres"
host = "pgs"
port = "5432"
storage = "sql"
user = ""
db_name = ""
password = ""
ssl_mode = "disable"
